version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:testpass123@db:5432/mydb"
    depends_on:
      - db
    command: bash -c "npx prisma migrate deploy && npx prisma generate && npm run div"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
